### PR TITLE
Fixes some Problems

### PR DESCRIPTION
**Pull request by Nightfly1704**
The Board Config didn't get saved implementet in Loop to save board_data.jsn
The StepSize wont be applied modifyed DriverBoard::initmove to apply the Stepsize
The LCD Page time couldnt be set from Management Page now Page time is applied but after reboot reset to 2 s still searching why ;)

### CODE REVIEW

**Comment by Nightfly1704** [comment]
I like your Project and i hpe this way is easyer for you to apply changes.

Best Regards 
Sven

**Comment by brownrb** [comment]
Thanks.
I prefer the old ways, as sometimes other stuff in the code might make things better
That is so with the lcd - we are using oled - so it should always have been oled, just my mess-up to
confuse the two.

1. It is probably better to remove all LCD and change to oled because the terminology is confusing.
2. You say stepsize but code sets stepmode so I assume that is a typo. I do not understand why stepmode needs to be set here in initmove. if stepmode changes in response to user request, stepmode gets applied immediately. I do not see anything in initmode() that is dependent upon stepmode. Can you please provide a reason for this?
3. The save config is best handled in the same manner as for the peristant and variable data, so it would be better placed into SetupData::SaveConfiguration so that there is consistency in the way data is saved and updated.

Thanks for the feedback, I do appreciate it.

**Comment by Nightfly1704** [comment]
Re: [brownrb/myFP2ESPFirmware] Fixes some Problems (#11)



Hello,

okay I will send new corrections with the Issues function.

Yes Stepmode. In my tests the stepmode is not set. The stepper is running in full step all the time. The M0 to M3 pins are all on LOW.
The stepmode is set correctly in the OLED, when I select 1/16 step the OLED shows me stepmode 16 but no change in the stepperdriver.
So I thought it would be a good idea to set this in the initmove function before the Motor moves , maybe the LoadConfiguration would
be good, but these Changes are only applied after a restart.

Best regards

Sven





Thanks.
I prefer the old ways, as sometimes other stuff in the code might make things better
That is so with the lcd - we are using oled - so it should always have been oled, just my mess-up to
confuse the two.

It is probably better to remove all LCD and change to oled because the terminology is confusing.
You say stepsize but code sets stepmode so I assume that is a typo. I do not understand why stepmode needs to be set here in initmove. if stepmode changes in response to user request, stepmode gets applied immediately. I do not see anything in initmode() that is dependent upon stepmode. Can you please provide a reason for this?
The save config is best handled in the same manner as for the peristant and variable data, so it would be better placed into SetupData::SaveConfiguration so that there is consistency in the way data is saved and updated.

Thanks for the feedback, I do appreciate it.

**Comment by Nightfly1704** [comment]
At start the Display Page time is set to 0 an Display runing wild, if you set Page time to x Seconds the Management server Sets the Value to 208.
mySetupData->set_oledpagetime(pgtime); should be mySetupData->set_oledpagetime((byte)pgtime); due to oledpagetime is an byte value an can't handle a long variable
Settmode istn applied, Stepper runs at full step

**Comment by Nightfly1704** [comment]
Board Config save failing 
Edited 
FocuserSetupData.cpp
Line 355 if ((BoardSnapShotMillis + DEFAULTSAVETIME) < x || BoardSnapShotMillis > x)    // 30s after snapshot
Line 356 {
Line 359     if (WriteBoardConfiguration() == false)
Line 371 }

WriteBoardConfiguration should be renamed to SaveBoardConfiguration 
SaveBoardConfiguration could be deleted time Management for Saving after 30 sec is now implementet throug SaveConfiguration in Loop. SaveBoardConfiguration only gets called one time through SaveConfiguratio so the if ((BoardSnapShotMillis + DEFAULTSAVETIME) < x || BoardSnapShotMillis > x)    // 30s after snapshot never happen.

**Comment by brownrb** [comment]
> 
> Re: [brownrb/myFP2ESPFirmware] Fixes some Problems (#11) Hello, okay I will send new corrections with the Issues function. Yes Stepmode. In my tests the stepmode is not set. The stepper is running in full step all the time. The M0 to M3 pins are all on LOW. The stepmode is set correctly in the OLED, when I select 1/16 step the OLED shows me stepmode 16 but no change in the stepperdriver. So I thought it would be a good idea to set this in the initmove function before the Motor moves , maybe the LoadConfiguration would be good, but these Changes are only applied after a restart. Best regards Sven Thanks. I prefer the old ways, as sometimes other stuff in the code might make things better That is so with the lcd - we are using oled - so it should always have been oled, just my mess-up to confuse the two. It is probably better to remove all LCD and change to oled because the terminology is confusing. You say stepsize but code sets stepmode so I assume that is a typo. I do not understand why stepmode needs to be set here in initmove. if stepmode changes in response to user request, stepmode gets applied immediately. I do not see anything in initmode() that is dependent upon stepmode. Can you please provide a reason for this? The save config is best handled in the same manner as for the peristant and variable data, so it would be better placed into SetupData::SaveConfiguration so that there is consistency in the way data is saved and updated. Thanks for the feedback, I do appreciate it. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

About stepmode.
The focuser works on the principle that setp mode should be :set and forget"
Any calls to set stepmode when the focuser is running, will come from comms.h or the management server, ascom server setup page or web server
1. comms.h
2. management server
3. ascom server
4. web server

Found issue.
Case 30 is invalid. Fix being applied now

This in fact had a few ripple effects through out the code.
boarddefs.h includes board definitions, speed definitions and stepmode definitions
the offendeding portions of code = the drvbd.equals was never upgraded to handle the
new way that we now handle boards.

**Comment by brownrb** [comment]
> 
> 
> Board Config save failing
> Edited
> FocuserSetupData.cpp
> Line 355 if ((BoardSnapShotMillis + DEFAULTSAVETIME) < x || BoardSnapShotMillis > x) // 30s after snapshot
> Line 356 {
> Line 359 if (WriteBoardConfiguration() == false)
> Line 371 }
> 
> WriteBoardConfiguration should be renamed to SaveBoardConfiguration
> SaveBoardConfiguration could be deleted time Management for Saving after 30 sec is now implementet throug SaveConfiguration in Loop. SaveBoardConfiguration only gets called one time through SaveConfiguratio so the if ((BoardSnapShotMillis + DEFAULTSAVETIME) < x || BoardSnapShotMillis > x) // 30s after snapshot never happen.


It looks like a little left over code on something that had changed my mind over and never went back to fix. I was using SaveBoard and WriteBoard in a different way when figuring out the code for generating and using board config files as they were to be called by the special html files used for board generation and config. i ended up changing how I did that so clearly I forgot to go back and address it. 

The WriteBoard.. yes should be called SaveBoard.. to be consistent will other usage. However the code in Writeboad.. is clearly wrong and needs to change because there is no need for another timeout test.
So I have recoded this to use the same style as that for handling data_var and data_per.

**Pull request closed without merging**
